### ISSUE TITLE
can't find version of keras_contrib 0.0.2

### ISSUE THREAD

**Issue by bluerxing** [JHL-HUST/ATDA#1]
Hi,

the requirements needs keras_contrib==0.0.2
I installed the one pip install git+https://www.github.com/keras-team/keras-contrib.git
the version is 2.0.8, I can't find version tag of 0.02 in github release and branch

Can you give the information where I can find 0.0.2 version?

Thanks

**Comment by cxmscb** [comment]
Hi,

I think it's OK to use the keras_contrib with the new version.

**Comment by bluerxing** [comment]
@cxmscb 
python -m train_atda models/modelZ_atda --type=0
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/xingpengwei/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xingpengwei/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xingpengwei/ATDA/train_atda.py", line 6, in <module>
    from cifar10 import *
  File "/home/xingpengwei/ATDA/cifar10.py", line 9, in <module>
    from keras_contrib.layers.normalization import GroupNormalization                                            
ImportError: cannot import name 'GroupNormalization'

it cannot. says: cannot import name 'GroupNormalization' from keras_contrib.layers.normalization import GroupNormalization

**Comment by cxmscb** [comment]
@bluerxing 
Hi, you can have a try: 
from keras_contrib.layers.normalization.groupnormalization import GroupNormalization

**Comment by bluerxing** [comment]
@cxmscb thanks, it works.
